name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main # Deploy when changes are pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Specify your Node.js version
          cache: "npm"

      # Step 3: Install dependencies and build the project
      - name: Install dependencies and build
        env:
          NEXT_RESEND_KEY: ${{ secrets.NEXT_RESEND_KEY }}
          NEXT_RESEND_KEY_GENERAL: ${{ secrets.NEXT_RESEND_KEY_GENERAL }}
          NEXT_RESEND_AUDIENCE_ID_GENERAL: ${{ secrets.NEXT_RESEND_AUDIENCE_ID_GENERAL }}
          NEXT_ANTHROPIC_KEY: ${{ secrets.NEXT_ANTHROPIC_KEY }}
          NEXT_MAILCHIMP_AUDIENCE_ID_DST: ${{ secrets.NEXT_MAILCHIMP_AUDIENCE_ID_DST }}
          NEXT_MAILCHIMP_KEY_GENERAL: ${{ secrets.NEXT_MAILCHIMP_KEY_GENERAL }}
        run: |
          npm install
          npm run build
        #   npm run export  # Exports static files to the `out` folder

      # Step 4: Deploy files via FTP
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          #   local-dir: ./out # Path to the exported static files
          server-dir: /public_html/drone-space # Target directory on the server
